#!/usr/bin/env bash
# uninstall.sh — reverse what install.sh set up.
#
# By default removes only the cross-harness symlinks + cron entry. Use --purge
# to also remove the source clone. The Claude marketplace + installed plugins
# are left alone unless --claude is passed (use `claude plugin uninstall` if
# you want to remove specific plugins).
#
# Usage:
#   bash scripts/uninstall.sh                # symlinks + cron (default)
#   bash scripts/uninstall.sh --cron-only    # cron entry only
#   bash scripts/uninstall.sh --symlinks-only
#   bash scripts/uninstall.sh --purge        # ALSO removes source clone
#   bash scripts/uninstall.sh --claude       # ALSO removes Claude marketplace + plugins
#   bash scripts/uninstall.sh --all          # everything (cross-harness + claude + clone)

set -euo pipefail

MARKETPLACE_SLUG="legion-core"
AGENTS_HOME="${AGENTS_HOME:-$HOME/.agents}"
SOURCE_CLONE="$AGENTS_HOME/sources/legion-core"
SKILLS_DIR="$AGENTS_HOME/skills"
LEGION_BIN_DIR="$AGENTS_HOME/bin"
BIN_MANIFEST="$AGENTS_HOME/.managed-by-legion-core/bins.txt"
MANIFEST="$AGENTS_HOME/.managed-by-legion-core/skills.txt"
CODEX_SKILLS_MANIFEST="$AGENTS_HOME/.managed-by-legion-core/codex-skills.txt"
CODEX_SKILLS_DIR="$HOME/.codex/skills"
# Legacy: the previous version generated wrapper files in ~/.codex/commands/ — clean those up too
CODEX_COMMANDS_MANIFEST="$AGENTS_HOME/.managed-by-legion-core/codex-commands.txt"
CODEX_COMMANDS_DIR="$HOME/.codex/commands"
CODEX_MARKER="<!-- legion-core-managed: do not edit; regenerated by install.sh -->"
CRON_TAG="# legion-core-refresh"

red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
dim()    { printf '\033[0;90m%s\033[0m\n' "$*"; }
bold()   { printf '\033[1m%s\033[0m\n' "$*"; }

DO_SYMLINKS=1
DO_CRON=1
DO_PURGE=0
DO_CLAUDE=0

for arg in "$@"; do
    case "$arg" in
        --cron-only)      DO_SYMLINKS=0; DO_CRON=1 ;;
        --symlinks-only)  DO_SYMLINKS=1; DO_CRON=0 ;;
        --purge)          DO_PURGE=1 ;;
        --claude)         DO_CLAUDE=1 ;;
        --all)            DO_PURGE=1; DO_CLAUDE=1 ;;
        -h|--help)        sed -n '/^# uninstall.sh/,/^# Usage/p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *)                red "Unknown flag: $arg"; exit 2 ;;
    esac
done

remove_symlinks() {
    [ "$DO_SYMLINKS" = "1" ] || return 0
    bold "Removing ~/.agents/skills/ symlinks managed by legion-core..."
    if [ ! -f "$MANIFEST" ]; then
        yellow "  · no manifest found at $MANIFEST — nothing to remove"
    else
        local count=0
        while IFS= read -r name; do
            local link="$SKILLS_DIR/$name"
            if [ -L "$link" ]; then
                rm "$link"
                count=$((count + 1))
            fi
        done < "$MANIFEST"
        rm -f "$MANIFEST"
        green "  ✔ removed $count symlinks"
    fi

    # Remove ~/.codex/skills/ symlinks managed by legion-core
    bold "Removing ~/.codex/skills/ symlinks managed by legion-core..."
    local codex_skill_count=0
    if [ -f "$CODEX_SKILLS_MANIFEST" ]; then
        while IFS= read -r name; do
            local link="$CODEX_SKILLS_DIR/$name"
            if [ -L "$link" ]; then
                rm "$link"
                codex_skill_count=$((codex_skill_count + 1))
            fi
        done < "$CODEX_SKILLS_MANIFEST"
        rm -f "$CODEX_SKILLS_MANIFEST"
        green "  ✔ removed $codex_skill_count Codex skill symlinks"
    else
        dim "  · no Codex skills manifest — nothing to remove"
    fi

    # Legacy cleanup: remove any leftover ~/.codex/commands/<name>.md stubs
    # from earlier install.sh versions that generated wrapper files there.
    if [ -f "$CODEX_COMMANDS_MANIFEST" ]; then
        local legacy_count=0
        while IFS= read -r name; do
            local cmd="$CODEX_COMMANDS_DIR/$name.md"
            if [ -f "$cmd" ] && grep -qF "$CODEX_MARKER" "$cmd" 2>/dev/null; then
                rm "$cmd"
                legacy_count=$((legacy_count + 1))
            fi
        done < "$CODEX_COMMANDS_MANIFEST"
        rm -f "$CODEX_COMMANDS_MANIFEST"
        [ "$legacy_count" -gt 0 ] && dim "  · legacy: removed $legacy_count old ~/.codex/commands/ wrappers"
    fi

    # Remove ~/.agents/bin/ CLI symlinks managed by legion-core
    bold "Removing ~/.agents/bin/ CLI symlinks managed by legion-core..."
    if [ -f "$BIN_MANIFEST" ]; then
        local bin_count=0
        while IFS= read -r cmd; do
            local link="$LEGION_BIN_DIR/$cmd"
            if [ -L "$link" ]; then
                rm "$link"
                bin_count=$((bin_count + 1))
            fi
        done < "$BIN_MANIFEST"
        rm -f "$BIN_MANIFEST"
        rmdir "$LEGION_BIN_DIR" 2>/dev/null || true
        green "  ✔ removed $bin_count CLI bins"
    else
        dim "  · no bins manifest — nothing to remove"
    fi

    rmdir "$AGENTS_HOME/.managed-by-legion-core" 2>/dev/null || true
}

remove_cron() {
    [ "$DO_CRON" = "1" ] || return 0
    bold "Removing daily refresh cron entry..."
    if crontab -l 2>/dev/null | grep -qF "$CRON_TAG"; then
        # `grep -vF` returns 1 when no lines remain (our entry was the only
        # one). With set -o pipefail that kills the script, so swallow.
        local remaining
        remaining="$(crontab -l 2>/dev/null | grep -vF "$CRON_TAG" || true)"
        if [ -n "$remaining" ]; then
            printf '%s\n' "$remaining" | crontab -
        else
            # Wipe the crontab entirely (no other entries to preserve)
            printf '' | crontab -
        fi
        green "  ✔ removed cron entry"
    else
        dim "  · no cron entry found — nothing to remove"
    fi
}

remove_source_clone() {
    [ "$DO_PURGE" = "1" ] || return 0
    bold "Removing source clone at $SOURCE_CLONE..."
    if [ -d "$SOURCE_CLONE" ]; then
        rm -rf "$SOURCE_CLONE"
        green "  ✔ removed"
    else
        dim "  · not present"
    fi
}

remove_claude_marketplace() {
    [ "$DO_CLAUDE" = "1" ] || return 0
    bold "Removing Claude marketplace + plugins..."
    if ! command -v claude >/dev/null 2>&1; then
        yellow "  · claude CLI not found — skipping"
        return 0
    fi
    # Uninstall each plugin from the marketplace, then remove the marketplace itself
    if claude plugin marketplace list 2>/dev/null | grep -q "$MARKETPLACE_SLUG"; then
        # `grep "@$MARKETPLACE_SLUG"` returns 1 when no plugins are installed (e.g.,
        # marketplace was registered but never had `plugin install` called). With
        # set -o pipefail that would kill the script — swallow with `|| true`.
        local installed
        installed="$(claude plugin list 2>/dev/null | grep "@$MARKETPLACE_SLUG" | awk '{print $2}' || true)"
        if [ -n "$installed" ]; then
            while IFS= read -r p; do
                if claude plugin uninstall "$p" 2>&1 | grep -q "✔"; then
                    green "  ✔ uninstalled $p"
                else
                    yellow "  · skip $p"
                fi
            done <<<"$installed"
        fi
        claude plugin marketplace remove "$MARKETPLACE_SLUG" 2>&1 | tail -1 || true
        green "  ✔ removed marketplace"
    else
        dim "  · marketplace not registered"
    fi
}

remove_symlinks
remove_cron
remove_source_clone
remove_claude_marketplace

bold "Done."
